name: Deploy Azure Function

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/functions/textToSpeech.js'
      - 'src/functions/text-helpers.js'
      - 'package.json'
      - 'package-lock.json'
      - 'host.json'
  workflow_dispatch: # Allow manual triggering

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install dependencies'
      run: npm ci

    - name: 'Azure CLI Login'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Function App'
      run: |
        npx func azure functionapp publish ${{ secrets.AZURE_FUNCTION_APP_NAME }} --javascript
      env:
        FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT: 1

    - name: 'Set Function App Settings'
      run: |
        az functionapp config appsettings set \
          --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
          --settings "GOOGLE_APPLICATION_CREDENTIALS_JSON=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"

    - name: 'Deployment Summary'
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "Function App: ${{ secrets.AZURE_FUNCTION_APP_NAME }}"
        echo "URL: https://${{ secrets.AZURE_FUNCTION_APP_NAME }}.azurewebsites.net/api/textToSpeech"